#!/bin/sh

# This script starts a session with the following windows:
#
# Window 1
# +-----------+-----------+---------+
# | rails     | console   |         |
# +-----------+-----------+  guard  |
# | shell     | shell     |         |
# +-----------+-----------+---------+
#
# Window 2
# +----------------+----------------+
# | redis          | sidekiq        |
# +----------------+----------------+
# | spring         | shell          |
# +----------------+----------------+

#######################
# kill existing stuff #
#######################

echo "waiting for processes to die..."
cd ~/work/tc-www
SKIP_YARN=1 bundle exec spring stop

pkill -f redis
pkill -f puma
pkill -f spring
pkill -f sidekiq

ps -ef | grep redis   | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep puma    | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep spring  | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep sidekiq | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep guard   | grep -v grep | awk '{print $2}' | xargs kill -9
sleep 1
tmux kill-session -t servers

#######################
# Window 1            #
#######################

# start a session
tmux new-session -d -s servers

# start the rails server (top left)
tmux send-keys 'SKIP_YARN=1 bundle exec rails s' 'C-m'
tmux rename-window 'rails-server'
tmux select-window -t servers:0

# split horizontally and open rails console (top center)
tmux split-window -h
tmux send-keys 'SKIP_YARN=1 bundle exec rails console' 'C-m'
tmux rename-window 'rails-console'

# split horizontally and start guard (top right)
tmux split-window -h
tmux rename-window 'guard'
tmux send-keys 'SKIP_YARN=1 bundle exec guard' 'C-m'

# resize equally along the horizontal axis:  |-----|--|--|  => |---|---|---|
tmux select-layout even-horizontal

# move to top left pane
tmux select-pane -L
tmux select-pane -L

# start shell (bottom left)  
tmux split-window
tmux rename-window 'shell2'

# start rails console (bottom center)
tmux select-pane -R
tmux split-window
tmux rename-window 'shell1'
tmux select-window -t servers:1

#######################
# Window 2            #
#######################

# open a second window
tmux new-window

# start redis (top left)
tmux send-keys 'redis-server' 'C-m'
tmux rename-window 'redis'

# split horizontally and start sidekiq
tmux split-window -h
tmux rename-window 'sidekiq'
tmux send-keys 'SKIP_YARN=1 bundle exec sidekiq' 'C-m'

# move to top-left pane
tmux select-pane -L

# start spring (bottom-left)
tmux split-window 
tmux rename-window 'spring'
tmux send-keys 'SKIP_YARN=1 bundle exec spring server' 'C-m'

# create empty pane (bottom-right)
tmux select-pane -U
tmux select-pane -R
tmux split-window
tmux rename-window 'shell4'

# resize equally
#tmux select-layout even-horizontal

#######################
# Attach              #
#######################

tmux attach-session -t servers
